---
abstract: 'Shell and Powershell pipes, haskell keywords mixed with the awesomeness of perl. forget shell scrpting now! '
author:
  - 'Marc Chantreux <khatar@phear.org>'
build_requires:
  Test::More: 0
  YAML: 0
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: perlude
requires:
  Carp: 0
  Exporter: 0
  Modern::Perl: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/eiro/p5-perlude
  repository: https://github.com/eiro/p5-perlude.git
version: 0.57
