---
abstract: 'an attempt to port a part of Haskell prelude in Perl'
author:
  - 'Marc Chantreux <marc.chantreux@biblibre.com>'
build_requires:
  Test::More: 0
  Test::Pod: 1.22
  YAML: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perlude
provides:
  Perlude:
    file: lib/Perlude.pm
    version: 0.50
resources:
  license: http://dev.perl.org/licenses/
version: 0.50
x_bugtracker: https://rt.cpan.org/Dist/Display.html?Queue=Perlude
x_homepage: https://github.com/eiro/p5-perlude
x_repository: https://github.com/eiro/p5-perlude.git
