---
abstract: 'Shell and Powershell pipes, haskell keywords mixed with the awesomeness of perl. forget shell scrpting now! '
author:
  - 'Marc Chantreux <khatar@phear.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: perlude
version: 0.54
